<?php

namespace App\Filament\User\Resources;

use App\Filament\User\Resources\CarResource\Pages;
use App\Filament\User\Resources\CarResource\RelationManagers;
use App\Infolists\Components\PriceEntry;
use App\Models\Car;
use Filament\Forms\Form;
use Filament\Infolists\Components\Grid;
use Filament\Infolists\Components\Group;
use Filament\Infolists\Components\SpatieMediaLibraryImageEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Infolists\Infolist;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class CarResource extends Resource
{
    protected static ?string $model = Car::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';


    public static function getModelLabel(): string
    {
        return __('Car');
    }

    public static function getPluralLabel(): ?string
    {
        return __('Cars');
    }

    public static function table(Table $table): Table
    {
        return $table
            ->content(view('car'))
            ->columns([
                //
            ])
            ->filters(
                Car::TableFilter()
                , Tables\Enums\FiltersLayout::AboveContent)
            ->actions([
                Tables\Actions\ViewAction::make(),
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                //

            ])->columns(3);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }


    public static function infolist(Infolist $infolist): Infolist
    {
        return $infolist->schema([
            Group::make([
                \Filament\Infolists\Components\Section::make(__('General Information'))->schema([
                    \Filament\Infolists\Components\Fieldset::make(__('Car Information'))->schema([
                        Grid::make(['default' => 2])->schema([

                            TextEntry::make('make')->badge()->translateLabel(),

                            TextEntry::make('model')->badge()->translateLabel(),

                            TextEntry::make('manufacturing_year')->badge()->translateLabel(),

                            TextEntry::make('body_style')->badge()->translateLabel(),
                            ]),
                    ]),
                    \Filament\Infolists\Components\Fieldset::make(__('Description'))->schema([
                        TextEntry::make('description')->columnSpanFull()->translateLabel(),
                        SpatieMediaLibraryImageEntry::make('image')
                            ->hiddenLabel()
                            ->collection('car_images')
                            ->columnSpanFull()
                            ->extraImgAttributes([
//                            'class' => 'w-full h-64 object-cover object-center',
                                'style' => "height: auto;width: 100%;"
                            ]),
                    ]),
                ]),
            ])->columnSpan(['lg' => 2]),
            Group::make([
                \Filament\Infolists\Components\Section::make(__('Specific Information'))->schema([
                    \Filament\Infolists\Components\Fieldset::make(__('Price'))->schema([
                        PriceEntry::make('price_per_day')->hiddenLabel()->columnSpanFull()->translateLabel()
                    ]),
                    \Filament\Infolists\Components\Fieldset::make(__('Car Details'))->schema([
                        Grid::make(['default' => 2])->schema([

                            TextEntry::make('color')->badge()->icon('tabler-color-swatch')->translateLabel(),
                            TextEntry::make('license_plate')->badge()->icon('tabler-id')->translateLabel(),
                            TextEntry::make('mileage')->badge()->icon('tabler-car')->prefix('km ')->translateLabel(),
                            TextEntry::make('mileage_to_service')->badge()->icon('tabler-car')->prefix('km ')->translateLabel(),
                            TextEntry::make('seats')->badge()->icon('tabler-armchair')->translateLabel(),
                            TextEntry::make('transmission_type')->badge()->icon('tabler-manual-gearbox')->translateLabel(),
                            TextEntry::make('fuel_type')->badge()->icon('tabler-gas-station')->translateLabel(),
                        ]),
                    ]),
                ]),
            ])->columnSpan(['lg' => 1]),

        ])->columns(3); // TODO: Change the autogenerated stub
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListCars::route('/'),
//            'create' => Pages\CreateCar::route('/create'),
            'view' => Pages\ViewCar::route('/{record}'),
            'edit' => Pages\EditCar::route('/{record}/edit'),
            'order' => Pages\OrderCar::route('/{record}/order'),
        ];
    }
}
